<?php

namespace Jm\SaleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FechaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FechaRepository extends EntityRepository
{
}
